require 'plugins/packer'
require 'plugins/telescope'
require 'plugins/hop'
require 'plugins/lsp'
require 'plugins/nvim-cmp'
require 'plugins/luasnip'
require 'plugins/treesitter'
-- require 'plugins/scrollbar'
require 'plugins/markdown-preview'
require 'plugins/catppuccin'
require 'settings'
